### ISSUE TITLE
[Feature Request] Templates

### ISSUE THREAD

**Issue by chrisburnor** [MrGVSV/bevy_proto#1]
An excellent feature would be the ability to use some entities as 'templates':

```
---
name: "Template Enemy"
components:
  - type: Enemy
```

Then using the template would be like:
```
---
name: "Enemy 1"
template: "Template Enemy"
components:
  - type: Attack
    value:
      damage: 10
  - type: Armed
    value:
      weapons: [ "laser sword", "ray-blaster" ]
      primary: "laser sword"
```

The result would insert components from the template into the specific instance of it.
