### ISSUE TITLE
bevy_proto_backend is pulling in every bevy feature

### ISSUE THREAD

**Issue by deifactor** [MrGVSV/bevy_proto#37]
I added

```toml
[dependencies.bevy_proto]
version = "0.9.0"
default-features = false
features = []
```

to my `Cargo.toml` and noticed it added a bunch of Bevy features I wasn't using (audio, gltf, etc). I think the root cause is that bevy_proto_backend has all the optional stuff in its default features, and bevy_proto doesn't disable default features.

Since it's a backend crate, maybe it makes sense to just not have any default features?
